package com.version2.lavithedam.styleandthemes

import android.os.Bundle
import android.support.v7.app.AppCompatActivity
import android.support.v7.widget.LinearLayoutManager
import android.support.v7.widget.RecyclerView
import com.version2.lavithedam.styleandthemes.Recycler.Avenger
import com.version2.lavithedam.styleandthemes.Recycler.AvengersAdapter

class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        var recyclerView = findViewById<RecyclerView>(R.id.listRecylcer)
        var layoutManager = LinearLayoutManager(this)
        recyclerView.layoutManager = layoutManager
        recyclerView.adapter = AvengersAdapter(createList())
    }

    fun createList(): ArrayList<Avenger> {
        var avengerList = ArrayList<Avenger>()
        avengerList.add(Avenger("Iron Man", "Robert Downey Jr", "https://www.google.co.in/imgres?imgurl=http://www.gstatic.com/tv/thumb/movieposters/170620/p170620_p_v8_ax.jpg&imgrefurl=http://google.com/search?tbm%3Disch%26q%3DIron%2520Man&h=1440&w=960&tbnid=b_w0xth6GdmbmM:&q=iron+man&tbnh=186&tbnw=124&usg=AFrqEzcsmfDIe0xXaV2z_IitLsYlcs9hpQ&vet=1&docid=f7WH5IKLKGJTuM&itg=1&sa=X&ved=2ahUKEwjApb_No-rcAhXL6Y8KHXc-DdoQ_B0wIHoECAYQCQ"))

        avengerList.add(Avenger("Captain America", "Chris Evans", "https://www.google.co.in/imgres?imgurl=https://upload.wikimedia.org/wikipedia/en/thumb/8/83/Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg/170px-Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg&imgrefurl=https://en.wikipedia.org/wiki/Captain_America&h=253&w=170&tbnid=P1x1ywOHmMfQ1M:&q=captain+america&tbnh=186&tbnw=124&usg=AFrqEzfP0-V0UGK8XYY99NETZNPZb3rGHA&vet=1&docid=dKFl1M2qzTEQ7M&itg=1&sa=X&ved=2ahUKEwjL3uKDpOrcAhXHQI8KHQpXBrUQ_B0wGXoECAgQCQ"))
        avengerList.add(Avenger("Iron Man", "Robert Downey Jr", "https://www.google.co.in/imgres?imgurl=http://www.gstatic.com/tv/thumb/movieposters/170620/p170620_p_v8_ax.jpg&imgrefurl=http://google.com/search?tbm%3Disch%26q%3DIron%2520Man&h=1440&w=960&tbnid=b_w0xth6GdmbmM:&q=iron+man&tbnh=186&tbnw=124&usg=AFrqEzcsmfDIe0xXaV2z_IitLsYlcs9hpQ&vet=1&docid=f7WH5IKLKGJTuM&itg=1&sa=X&ved=2ahUKEwjApb_No-rcAhXL6Y8KHXc-DdoQ_B0wIHoECAYQCQ"))

        avengerList.add(Avenger("Captain America", "Chris Evans", "https://www.google.co.in/imgres?imgurl=https://upload.wikimedia.org/wikipedia/en/thumb/8/83/Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg/170px-Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg&imgrefurl=https://en.wikipedia.org/wiki/Captain_America&h=253&w=170&tbnid=P1x1ywOHmMfQ1M:&q=captain+america&tbnh=186&tbnw=124&usg=AFrqEzfP0-V0UGK8XYY99NETZNPZb3rGHA&vet=1&docid=dKFl1M2qzTEQ7M&itg=1&sa=X&ved=2ahUKEwjL3uKDpOrcAhXHQI8KHQpXBrUQ_B0wGXoECAgQCQ"))
        avengerList.add(Avenger("Iron Man", "Robert Downey Jr", "https://www.google.co.in/imgres?imgurl=http://www.gstatic.com/tv/thumb/movieposters/170620/p170620_p_v8_ax.jpg&imgrefurl=http://google.com/search?tbm%3Disch%26q%3DIron%2520Man&h=1440&w=960&tbnid=b_w0xth6GdmbmM:&q=iron+man&tbnh=186&tbnw=124&usg=AFrqEzcsmfDIe0xXaV2z_IitLsYlcs9hpQ&vet=1&docid=f7WH5IKLKGJTuM&itg=1&sa=X&ved=2ahUKEwjApb_No-rcAhXL6Y8KHXc-DdoQ_B0wIHoECAYQCQ"))

        avengerList.add(Avenger("Captain America", "Chris Evans", "https://www.google.co.in/imgres?imgurl=https://upload.wikimedia.org/wikipedia/en/thumb/8/83/Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg/170px-Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg&imgrefurl=https://en.wikipedia.org/wiki/Captain_America&h=253&w=170&tbnid=P1x1ywOHmMfQ1M:&q=captain+america&tbnh=186&tbnw=124&usg=AFrqEzfP0-V0UGK8XYY99NETZNPZb3rGHA&vet=1&docid=dKFl1M2qzTEQ7M&itg=1&sa=X&ved=2ahUKEwjL3uKDpOrcAhXHQI8KHQpXBrUQ_B0wGXoECAgQCQ"))
        avengerList.add(Avenger("Iron Man", "Robert Downey Jr", "https://www.google.co.in/imgres?imgurl=http://www.gstatic.com/tv/thumb/movieposters/170620/p170620_p_v8_ax.jpg&imgrefurl=http://google.com/search?tbm%3Disch%26q%3DIron%2520Man&h=1440&w=960&tbnid=b_w0xth6GdmbmM:&q=iron+man&tbnh=186&tbnw=124&usg=AFrqEzcsmfDIe0xXaV2z_IitLsYlcs9hpQ&vet=1&docid=f7WH5IKLKGJTuM&itg=1&sa=X&ved=2ahUKEwjApb_No-rcAhXL6Y8KHXc-DdoQ_B0wIHoECAYQCQ"))

        avengerList.add(Avenger("Captain America", "Chris Evans", "https://www.google.co.in/imgres?imgurl=https://upload.wikimedia.org/wikipedia/en/thumb/8/83/Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg/170px-Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg&imgrefurl=https://en.wikipedia.org/wiki/Captain_America&h=253&w=170&tbnid=P1x1ywOHmMfQ1M:&q=captain+america&tbnh=186&tbnw=124&usg=AFrqEzfP0-V0UGK8XYY99NETZNPZb3rGHA&vet=1&docid=dKFl1M2qzTEQ7M&itg=1&sa=X&ved=2ahUKEwjL3uKDpOrcAhXHQI8KHQpXBrUQ_B0wGXoECAgQCQ"))
        avengerList.add(Avenger("Iron Man", "Robert Downey Jr", "https://www.google.co.in/imgres?imgurl=http://www.gstatic.com/tv/thumb/movieposters/170620/p170620_p_v8_ax.jpg&imgrefurl=http://google.com/search?tbm%3Disch%26q%3DIron%2520Man&h=1440&w=960&tbnid=b_w0xth6GdmbmM:&q=iron+man&tbnh=186&tbnw=124&usg=AFrqEzcsmfDIe0xXaV2z_IitLsYlcs9hpQ&vet=1&docid=f7WH5IKLKGJTuM&itg=1&sa=X&ved=2ahUKEwjApb_No-rcAhXL6Y8KHXc-DdoQ_B0wIHoECAYQCQ"))

        avengerList.add(Avenger("Captain America", "Chris Evans", "https://www.google.co.in/imgres?imgurl=https://upload.wikimedia.org/wikipedia/en/thumb/8/83/Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg/170px-Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg&imgrefurl=https://en.wikipedia.org/wiki/Captain_America&h=253&w=170&tbnid=P1x1ywOHmMfQ1M:&q=captain+america&tbnh=186&tbnw=124&usg=AFrqEzfP0-V0UGK8XYY99NETZNPZb3rGHA&vet=1&docid=dKFl1M2qzTEQ7M&itg=1&sa=X&ved=2ahUKEwjL3uKDpOrcAhXHQI8KHQpXBrUQ_B0wGXoECAgQCQ"))
        avengerList.add(Avenger("Iron Man", "Robert Downey Jr", "https://www.google.co.in/imgres?imgurl=http://www.gstatic.com/tv/thumb/movieposters/170620/p170620_p_v8_ax.jpg&imgrefurl=http://google.com/search?tbm%3Disch%26q%3DIron%2520Man&h=1440&w=960&tbnid=b_w0xth6GdmbmM:&q=iron+man&tbnh=186&tbnw=124&usg=AFrqEzcsmfDIe0xXaV2z_IitLsYlcs9hpQ&vet=1&docid=f7WH5IKLKGJTuM&itg=1&sa=X&ved=2ahUKEwjApb_No-rcAhXL6Y8KHXc-DdoQ_B0wIHoECAYQCQ"))

        avengerList.add(Avenger("Captain America", "Chris Evans", "https://www.google.co.in/imgres?imgurl=https://upload.wikimedia.org/wikipedia/en/thumb/8/83/Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg/170px-Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg&imgrefurl=https://en.wikipedia.org/wiki/Captain_America&h=253&w=170&tbnid=P1x1ywOHmMfQ1M:&q=captain+america&tbnh=186&tbnw=124&usg=AFrqEzfP0-V0UGK8XYY99NETZNPZb3rGHA&vet=1&docid=dKFl1M2qzTEQ7M&itg=1&sa=X&ved=2ahUKEwjL3uKDpOrcAhXHQI8KHQpXBrUQ_B0wGXoECAgQCQ"))
        avengerList.add(Avenger("Iron Man", "Robert Downey Jr", "https://www.google.co.in/imgres?imgurl=http://www.gstatic.com/tv/thumb/movieposters/170620/p170620_p_v8_ax.jpg&imgrefurl=http://google.com/search?tbm%3Disch%26q%3DIron%2520Man&h=1440&w=960&tbnid=b_w0xth6GdmbmM:&q=iron+man&tbnh=186&tbnw=124&usg=AFrqEzcsmfDIe0xXaV2z_IitLsYlcs9hpQ&vet=1&docid=f7WH5IKLKGJTuM&itg=1&sa=X&ved=2ahUKEwjApb_No-rcAhXL6Y8KHXc-DdoQ_B0wIHoECAYQCQ"))

        avengerList.add(Avenger("Captain America", "Chris Evans", "https://www.google.co.in/imgres?imgurl=https://upload.wikimedia.org/wikipedia/en/thumb/8/83/Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg/170px-Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg&imgrefurl=https://en.wikipedia.org/wiki/Captain_America&h=253&w=170&tbnid=P1x1ywOHmMfQ1M:&q=captain+america&tbnh=186&tbnw=124&usg=AFrqEzfP0-V0UGK8XYY99NETZNPZb3rGHA&vet=1&docid=dKFl1M2qzTEQ7M&itg=1&sa=X&ved=2ahUKEwjL3uKDpOrcAhXHQI8KHQpXBrUQ_B0wGXoECAgQCQ"))
        avengerList.add(Avenger("Iron Man", "Robert Downey Jr", "https://www.google.co.in/imgres?imgurl=http://www.gstatic.com/tv/thumb/movieposters/170620/p170620_p_v8_ax.jpg&imgrefurl=http://google.com/search?tbm%3Disch%26q%3DIron%2520Man&h=1440&w=960&tbnid=b_w0xth6GdmbmM:&q=iron+man&tbnh=186&tbnw=124&usg=AFrqEzcsmfDIe0xXaV2z_IitLsYlcs9hpQ&vet=1&docid=f7WH5IKLKGJTuM&itg=1&sa=X&ved=2ahUKEwjApb_No-rcAhXL6Y8KHXc-DdoQ_B0wIHoECAYQCQ"))

        avengerList.add(Avenger("Captain America", "Chris Evans", "https://www.google.co.in/imgres?imgurl=https://upload.wikimedia.org/wikipedia/en/thumb/8/83/Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg/170px-Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg&imgrefurl=https://en.wikipedia.org/wiki/Captain_America&h=253&w=170&tbnid=P1x1ywOHmMfQ1M:&q=captain+america&tbnh=186&tbnw=124&usg=AFrqEzfP0-V0UGK8XYY99NETZNPZb3rGHA&vet=1&docid=dKFl1M2qzTEQ7M&itg=1&sa=X&ved=2ahUKEwjL3uKDpOrcAhXHQI8KHQpXBrUQ_B0wGXoECAgQCQ"))
        avengerList.add(Avenger("Iron Man", "Robert Downey Jr", "https://www.google.co.in/imgres?imgurl=http://www.gstatic.com/tv/thumb/movieposters/170620/p170620_p_v8_ax.jpg&imgrefurl=http://google.com/search?tbm%3Disch%26q%3DIron%2520Man&h=1440&w=960&tbnid=b_w0xth6GdmbmM:&q=iron+man&tbnh=186&tbnw=124&usg=AFrqEzcsmfDIe0xXaV2z_IitLsYlcs9hpQ&vet=1&docid=f7WH5IKLKGJTuM&itg=1&sa=X&ved=2ahUKEwjApb_No-rcAhXL6Y8KHXc-DdoQ_B0wIHoECAYQCQ"))

        avengerList.add(Avenger("Captain America", "Chris Evans", "https://www.google.co.in/imgres?imgurl=https://upload.wikimedia.org/wikipedia/en/thumb/8/83/Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg/170px-Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg&imgrefurl=https://en.wikipedia.org/wiki/Captain_America&h=253&w=170&tbnid=P1x1ywOHmMfQ1M:&q=captain+america&tbnh=186&tbnw=124&usg=AFrqEzfP0-V0UGK8XYY99NETZNPZb3rGHA&vet=1&docid=dKFl1M2qzTEQ7M&itg=1&sa=X&ved=2ahUKEwjL3uKDpOrcAhXHQI8KHQpXBrUQ_B0wGXoECAgQCQ"))
        avengerList.add(Avenger("Iron Man", "Robert Downey Jr", "https://www.google.co.in/imgres?imgurl=http://www.gstatic.com/tv/thumb/movieposters/170620/p170620_p_v8_ax.jpg&imgrefurl=http://google.com/search?tbm%3Disch%26q%3DIron%2520Man&h=1440&w=960&tbnid=b_w0xth6GdmbmM:&q=iron+man&tbnh=186&tbnw=124&usg=AFrqEzcsmfDIe0xXaV2z_IitLsYlcs9hpQ&vet=1&docid=f7WH5IKLKGJTuM&itg=1&sa=X&ved=2ahUKEwjApb_No-rcAhXL6Y8KHXc-DdoQ_B0wIHoECAYQCQ"))

        avengerList.add(Avenger("Captain America", "Chris Evans", "https://www.google.co.in/imgres?imgurl=https://upload.wikimedia.org/wikipedia/en/thumb/8/83/Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg/170px-Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg&imgrefurl=https://en.wikipedia.org/wiki/Captain_America&h=253&w=170&tbnid=P1x1ywOHmMfQ1M:&q=captain+america&tbnh=186&tbnw=124&usg=AFrqEzfP0-V0UGK8XYY99NETZNPZb3rGHA&vet=1&docid=dKFl1M2qzTEQ7M&itg=1&sa=X&ved=2ahUKEwjL3uKDpOrcAhXHQI8KHQpXBrUQ_B0wGXoECAgQCQ"))
        avengerList.add(Avenger("Iron Man", "Robert Downey Jr", "https://www.google.co.in/imgres?imgurl=http://www.gstatic.com/tv/thumb/movieposters/170620/p170620_p_v8_ax.jpg&imgrefurl=http://google.com/search?tbm%3Disch%26q%3DIron%2520Man&h=1440&w=960&tbnid=b_w0xth6GdmbmM:&q=iron+man&tbnh=186&tbnw=124&usg=AFrqEzcsmfDIe0xXaV2z_IitLsYlcs9hpQ&vet=1&docid=f7WH5IKLKGJTuM&itg=1&sa=X&ved=2ahUKEwjApb_No-rcAhXL6Y8KHXc-DdoQ_B0wIHoECAYQCQ"))

        avengerList.add(Avenger("Captain America", "Chris Evans", "https://www.google.co.in/imgres?imgurl=https://upload.wikimedia.org/wikipedia/en/thumb/8/83/Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg/170px-Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg&imgrefurl=https://en.wikipedia.org/wiki/Captain_America&h=253&w=170&tbnid=P1x1ywOHmMfQ1M:&q=captain+america&tbnh=186&tbnw=124&usg=AFrqEzfP0-V0UGK8XYY99NETZNPZb3rGHA&vet=1&docid=dKFl1M2qzTEQ7M&itg=1&sa=X&ved=2ahUKEwjL3uKDpOrcAhXHQI8KHQpXBrUQ_B0wGXoECAgQCQ"))
        avengerList.add(Avenger("Iron Man", "Robert Downey Jr", "https://www.google.co.in/imgres?imgurl=http://www.gstatic.com/tv/thumb/movieposters/170620/p170620_p_v8_ax.jpg&imgrefurl=http://google.com/search?tbm%3Disch%26q%3DIron%2520Man&h=1440&w=960&tbnid=b_w0xth6GdmbmM:&q=iron+man&tbnh=186&tbnw=124&usg=AFrqEzcsmfDIe0xXaV2z_IitLsYlcs9hpQ&vet=1&docid=f7WH5IKLKGJTuM&itg=1&sa=X&ved=2ahUKEwjApb_No-rcAhXL6Y8KHXc-DdoQ_B0wIHoECAYQCQ"))

        avengerList.add(Avenger("Captain America", "Chris Evans", "https://www.google.co.in/imgres?imgurl=https://upload.wikimedia.org/wikipedia/en/thumb/8/83/Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg/170px-Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg&imgrefurl=https://en.wikipedia.org/wiki/Captain_America&h=253&w=170&tbnid=P1x1ywOHmMfQ1M:&q=captain+america&tbnh=186&tbnw=124&usg=AFrqEzfP0-V0UGK8XYY99NETZNPZb3rGHA&vet=1&docid=dKFl1M2qzTEQ7M&itg=1&sa=X&ved=2ahUKEwjL3uKDpOrcAhXHQI8KHQpXBrUQ_B0wGXoECAgQCQ"))
        avengerList.add(Avenger("Iron Man", "Robert Downey Jr", "https://www.google.co.in/imgres?imgurl=http://www.gstatic.com/tv/thumb/movieposters/170620/p170620_p_v8_ax.jpg&imgrefurl=http://google.com/search?tbm%3Disch%26q%3DIron%2520Man&h=1440&w=960&tbnid=b_w0xth6GdmbmM:&q=iron+man&tbnh=186&tbnw=124&usg=AFrqEzcsmfDIe0xXaV2z_IitLsYlcs9hpQ&vet=1&docid=f7WH5IKLKGJTuM&itg=1&sa=X&ved=2ahUKEwjApb_No-rcAhXL6Y8KHXc-DdoQ_B0wIHoECAYQCQ"))

        avengerList.add(Avenger("Captain America", "Chris Evans", "https://www.google.co.in/imgres?imgurl=https://upload.wikimedia.org/wikipedia/en/thumb/8/83/Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg/170px-Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg&imgrefurl=https://en.wikipedia.org/wiki/Captain_America&h=253&w=170&tbnid=P1x1ywOHmMfQ1M:&q=captain+america&tbnh=186&tbnw=124&usg=AFrqEzfP0-V0UGK8XYY99NETZNPZb3rGHA&vet=1&docid=dKFl1M2qzTEQ7M&itg=1&sa=X&ved=2ahUKEwjL3uKDpOrcAhXHQI8KHQpXBrUQ_B0wGXoECAgQCQ"))
        avengerList.add(Avenger("Iron Man", "Robert Downey Jr", "https://www.google.co.in/imgres?imgurl=http://www.gstatic.com/tv/thumb/movieposters/170620/p170620_p_v8_ax.jpg&imgrefurl=http://google.com/search?tbm%3Disch%26q%3DIron%2520Man&h=1440&w=960&tbnid=b_w0xth6GdmbmM:&q=iron+man&tbnh=186&tbnw=124&usg=AFrqEzcsmfDIe0xXaV2z_IitLsYlcs9hpQ&vet=1&docid=f7WH5IKLKGJTuM&itg=1&sa=X&ved=2ahUKEwjApb_No-rcAhXL6Y8KHXc-DdoQ_B0wIHoECAYQCQ"))

        avengerList.add(Avenger("Captain America", "Chris Evans", "https://www.google.co.in/imgres?imgurl=https://upload.wikimedia.org/wikipedia/en/thumb/8/83/Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg/170px-Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg&imgrefurl=https://en.wikipedia.org/wiki/Captain_America&h=253&w=170&tbnid=P1x1ywOHmMfQ1M:&q=captain+america&tbnh=186&tbnw=124&usg=AFrqEzfP0-V0UGK8XYY99NETZNPZb3rGHA&vet=1&docid=dKFl1M2qzTEQ7M&itg=1&sa=X&ved=2ahUKEwjL3uKDpOrcAhXHQI8KHQpXBrUQ_B0wGXoECAgQCQ"))
        avengerList.add(Avenger("Iron Man", "Robert Downey Jr", "https://www.google.co.in/imgres?imgurl=http://www.gstatic.com/tv/thumb/movieposters/170620/p170620_p_v8_ax.jpg&imgrefurl=http://google.com/search?tbm%3Disch%26q%3DIron%2520Man&h=1440&w=960&tbnid=b_w0xth6GdmbmM:&q=iron+man&tbnh=186&tbnw=124&usg=AFrqEzcsmfDIe0xXaV2z_IitLsYlcs9hpQ&vet=1&docid=f7WH5IKLKGJTuM&itg=1&sa=X&ved=2ahUKEwjApb_No-rcAhXL6Y8KHXc-DdoQ_B0wIHoECAYQCQ"))

        avengerList.add(Avenger("Captain America", "Chris Evans", "https://www.google.co.in/imgres?imgurl=https://upload.wikimedia.org/wikipedia/en/thumb/8/83/Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg/170px-Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg&imgrefurl=https://en.wikipedia.org/wiki/Captain_America&h=253&w=170&tbnid=P1x1ywOHmMfQ1M:&q=captain+america&tbnh=186&tbnw=124&usg=AFrqEzfP0-V0UGK8XYY99NETZNPZb3rGHA&vet=1&docid=dKFl1M2qzTEQ7M&itg=1&sa=X&ved=2ahUKEwjL3uKDpOrcAhXHQI8KHQpXBrUQ_B0wGXoECAgQCQ"))
        avengerList.add(Avenger("Iron Man", "Robert Downey Jr", "https://www.google.co.in/imgres?imgurl=http://www.gstatic.com/tv/thumb/movieposters/170620/p170620_p_v8_ax.jpg&imgrefurl=http://google.com/search?tbm%3Disch%26q%3DIron%2520Man&h=1440&w=960&tbnid=b_w0xth6GdmbmM:&q=iron+man&tbnh=186&tbnw=124&usg=AFrqEzcsmfDIe0xXaV2z_IitLsYlcs9hpQ&vet=1&docid=f7WH5IKLKGJTuM&itg=1&sa=X&ved=2ahUKEwjApb_No-rcAhXL6Y8KHXc-DdoQ_B0wIHoECAYQCQ"))

        avengerList.add(Avenger("Captain America", "Chris Evans", "https://www.google.co.in/imgres?imgurl=https://upload.wikimedia.org/wikipedia/en/thumb/8/83/Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg/170px-Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg&imgrefurl=https://en.wikipedia.org/wiki/Captain_America&h=253&w=170&tbnid=P1x1ywOHmMfQ1M:&q=captain+america&tbnh=186&tbnw=124&usg=AFrqEzfP0-V0UGK8XYY99NETZNPZb3rGHA&vet=1&docid=dKFl1M2qzTEQ7M&itg=1&sa=X&ved=2ahUKEwjL3uKDpOrcAhXHQI8KHQpXBrUQ_B0wGXoECAgQCQ"))
        avengerList.add(Avenger("Iron Man", "Robert Downey Jr", "https://www.google.co.in/imgres?imgurl=http://www.gstatic.com/tv/thumb/movieposters/170620/p170620_p_v8_ax.jpg&imgrefurl=http://google.com/search?tbm%3Disch%26q%3DIron%2520Man&h=1440&w=960&tbnid=b_w0xth6GdmbmM:&q=iron+man&tbnh=186&tbnw=124&usg=AFrqEzcsmfDIe0xXaV2z_IitLsYlcs9hpQ&vet=1&docid=f7WH5IKLKGJTuM&itg=1&sa=X&ved=2ahUKEwjApb_No-rcAhXL6Y8KHXc-DdoQ_B0wIHoECAYQCQ"))

        avengerList.add(Avenger("Captain America", "Chris Evans", "https://www.google.co.in/imgres?imgurl=https://upload.wikimedia.org/wikipedia/en/thumb/8/83/Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg/170px-Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg&imgrefurl=https://en.wikipedia.org/wiki/Captain_America&h=253&w=170&tbnid=P1x1ywOHmMfQ1M:&q=captain+america&tbnh=186&tbnw=124&usg=AFrqEzfP0-V0UGK8XYY99NETZNPZb3rGHA&vet=1&docid=dKFl1M2qzTEQ7M&itg=1&sa=X&ved=2ahUKEwjL3uKDpOrcAhXHQI8KHQpXBrUQ_B0wGXoECAgQCQ"))
        avengerList.add(Avenger("Iron Man", "Robert Downey Jr", "https://www.google.co.in/imgres?imgurl=http://www.gstatic.com/tv/thumb/movieposters/170620/p170620_p_v8_ax.jpg&imgrefurl=http://google.com/search?tbm%3Disch%26q%3DIron%2520Man&h=1440&w=960&tbnid=b_w0xth6GdmbmM:&q=iron+man&tbnh=186&tbnw=124&usg=AFrqEzcsmfDIe0xXaV2z_IitLsYlcs9hpQ&vet=1&docid=f7WH5IKLKGJTuM&itg=1&sa=X&ved=2ahUKEwjApb_No-rcAhXL6Y8KHXc-DdoQ_B0wIHoECAYQCQ"))

        avengerList.add(Avenger("Captain America", "Chris Evans", "https://www.google.co.in/imgres?imgurl=https://upload.wikimedia.org/wikipedia/en/thumb/8/83/Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg/170px-Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg&imgrefurl=https://en.wikipedia.org/wiki/Captain_America&h=253&w=170&tbnid=P1x1ywOHmMfQ1M:&q=captain+america&tbnh=186&tbnw=124&usg=AFrqEzfP0-V0UGK8XYY99NETZNPZb3rGHA&vet=1&docid=dKFl1M2qzTEQ7M&itg=1&sa=X&ved=2ahUKEwjL3uKDpOrcAhXHQI8KHQpXBrUQ_B0wGXoECAgQCQ"))
        avengerList.add(Avenger("Iron Man", "Robert Downey Jr", "https://www.google.co.in/imgres?imgurl=http://www.gstatic.com/tv/thumb/movieposters/170620/p170620_p_v8_ax.jpg&imgrefurl=http://google.com/search?tbm%3Disch%26q%3DIron%2520Man&h=1440&w=960&tbnid=b_w0xth6GdmbmM:&q=iron+man&tbnh=186&tbnw=124&usg=AFrqEzcsmfDIe0xXaV2z_IitLsYlcs9hpQ&vet=1&docid=f7WH5IKLKGJTuM&itg=1&sa=X&ved=2ahUKEwjApb_No-rcAhXL6Y8KHXc-DdoQ_B0wIHoECAYQCQ"))

        avengerList.add(Avenger("Captain America", "Chris Evans", "https://www.google.co.in/imgres?imgurl=https://upload.wikimedia.org/wikipedia/en/thumb/8/83/Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg/170px-Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg&imgrefurl=https://en.wikipedia.org/wiki/Captain_America&h=253&w=170&tbnid=P1x1ywOHmMfQ1M:&q=captain+america&tbnh=186&tbnw=124&usg=AFrqEzfP0-V0UGK8XYY99NETZNPZb3rGHA&vet=1&docid=dKFl1M2qzTEQ7M&itg=1&sa=X&ved=2ahUKEwjL3uKDpOrcAhXHQI8KHQpXBrUQ_B0wGXoECAgQCQ"))
        avengerList.add(Avenger("Iron Man", "Robert Downey Jr", "https://www.google.co.in/imgres?imgurl=http://www.gstatic.com/tv/thumb/movieposters/170620/p170620_p_v8_ax.jpg&imgrefurl=http://google.com/search?tbm%3Disch%26q%3DIron%2520Man&h=1440&w=960&tbnid=b_w0xth6GdmbmM:&q=iron+man&tbnh=186&tbnw=124&usg=AFrqEzcsmfDIe0xXaV2z_IitLsYlcs9hpQ&vet=1&docid=f7WH5IKLKGJTuM&itg=1&sa=X&ved=2ahUKEwjApb_No-rcAhXL6Y8KHXc-DdoQ_B0wIHoECAYQCQ"))

        avengerList.add(Avenger("Captain America", "Chris Evans", "https://www.google.co.in/imgres?imgurl=https://upload.wikimedia.org/wikipedia/en/thumb/8/83/Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg/170px-Captain_America_%2528Steve_Rogers%2529_All_New_All_Different_Marvel_version.jpg&imgrefurl=https://en.wikipedia.org/wiki/Captain_America&h=253&w=170&tbnid=P1x1ywOHmMfQ1M:&q=captain+america&tbnh=186&tbnw=124&usg=AFrqEzfP0-V0UGK8XYY99NETZNPZb3rGHA&vet=1&docid=dKFl1M2qzTEQ7M&itg=1&sa=X&ved=2ahUKEwjL3uKDpOrcAhXHQI8KHQpXBrUQ_B0wGXoECAgQCQ"))

        return avengerList
    }
}
